spring:
  application:
    name: classroom
  datasource:
    url: jdbc:postgresql://localhost:5432/Tronco
    username: admin2
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    credentials:
      access-key: AKIA5CBGTLP7RMQPCJPO
      secret-key: 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
    s3:
      region: eu-west-3
